name: Manual Execute All Notebooks
on:
  workflow_dispatch:

jobs:
  ExecuteNotebooks:
   uses: spacetelescope/notebook-ci-actions/.github/workflows/ci_scheduled.yml@v3
   with:
      python-version: ${{ vars.PYTHON_VERSION }}
   secrets:
      CASJOBS_PW: ${{ secrets.CASJOBS_PW }}
      CASJOBS_USERID: ${{ secrets.CASJOBS_USERID }}
   permissions:
     contents: write
