name: Manual Notebook Execution
on:
  workflow_dispatch:
  
env:
  CASJOBS_PW: ${{ secrets.CASJOBS_PW }}
  CASJOBS_USERID: ${{ secrets.CASJOBS_USERID }}
  
jobs:
  ScheduledBuild:
   uses: dulude/notebook-ci-actions/.github/workflows/ci_scheduled.yml@main
